name: 'OpenVPN Connect'
description: 'Connect to OpenVPN using provided config and credentials'
author: "secouvreur"
inputs:
  vpn_config:
    description: 'OpenVPN config file content'
    required: true
  vpn_username:
    description: 'VPN username (optional)'
    required: false
  vpn_password:
    description: 'VPN password (optional)'
    required: false
  timeout:
    description: 'Connection timeout in seconds'
    required: false
    default: 15
runs:
  using: "composite"
  steps:
    - name: Install OpenVPN
      shell: bash
      run: sudo apt-get install -y openvpn

    - name: Create VPN config and auth files if needed
      shell: bash
      run: |
        echo "${{ inputs.vpn_config }}" > vpn-config.ovpn
        if [[ -n "${{ inputs.vpn_username }}" && -n "${{ inputs.vpn_password }}" ]]; then
          echo "${{ inputs.vpn_username }}" > vpn-auth.txt
          echo "${{ inputs.vpn_password }}" >> vpn-auth.txt
          echo "auth-user-pass vpn-auth.txt" >> vpn-config.ovpn
        fi

    - name: Connect to VPN
      shell: bash
      run: |
        sudo openvpn --config vpn-config.ovpn --daemon --log /tmp/openvpn.log
      continue-on-error: true

    - name: Wait for VPN connection
      id: check-vpn-status
      shell: bash
      continue-on-error: true
      run: |
        for i in {1..${{ inputs.timeout }}}; do
          if ifconfig tun0 2>/dev/null || ip link show tun0 2>/dev/null; then
            echo "VPN is up."
            break
          fi
          echo "Waiting for VPN to come up..."
          sleep 1
        done

        if ! ifconfig tun0 2>/dev/null && ! ip link show tun0 2>/dev/null; then
          echo "VPN connection failed."
          sudo cat /tmp/openvpn.log > /tmp/openvpn-artifact.log
          exit 1
        fi

    - name: Upload OpenVPN log if VPN connection failed
      if: steps.check-vpn-status.outcome == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: openvpn-log
        path: /tmp/openvpn-artifact.log

    - name: Fail the Job if no VPN connection
      if: steps.check-vpn-status.outcome == 'failure'
      shell: bash
      run: exit 1